version: '3.8'
services:
  web:
    container_name: web
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./data