version: '3.8'
services:
  web:
    container_name: web
    build: .
    command: uvicorn main:app --host 0.0.0.0
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - geonet
    depends_on:
      - mongo
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/var/lib/mongo/data
    networks:
      - geonet
networks:
  geonet: {}
volumes:
  mongo_data: